[ font ]
size = 15 

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = '\'
key = "¥"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"
