## Escキーの遅延を解消
set -s escape-time 0

# tmux起動時のシェルをzshにする
set-option -g default-shell /bin/zsh

# tmuxを256色表示できるようにする
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# ステータスバーをトップに配置する
set-option -g status-position top

# ステータスバーを1秒毎に描画し直す
set-option -g status-interval 1

# ステータスバーの色を設定する
set-option -g status-bg "colour238"

# status line の文字色を指定する。
set-option -g status-fg "colour255"

# コピーモードを設定する
# コピーモードでvimキーバインドを使う
setw -g mode-keys vi

## 非アクティブを白
set -g window-style 'bg=colour239'
set -g window-active-style 'bg=colour234'

## 非アクティブを薄い黒
#set -g window-style 'fg='colour244,bg=colour234'
#set -g window-active-style 'fg=white,bg=black'

## historyを10000行に設定
set-option g history-limit 10000

### tmux セッション保存
# https://takezoe.hatenablog.com/entry/2015/09/04/100132
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# logging 
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @logging-path "$HOME/log/tmux/%Y-%m-%d"
set -g @logging-filename "#{session_name}-#{window-_name}-#{pane_index}.log"

run '~/.tmux/plugins/tpm/tpm'

# tmux source ~/.tmux.conf を実行して読み込む
