### Environment
# Language
export LANG=ja_JP.UTF-8
# ローカルコマンド追加
export PATH="${PATH}:/Users/${USER}/bin"
# ヒストリの設定
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=100000

### Alias
alias history='history -t "%F %T"'
alias ll='ls -ltr'

### zsh
# 時間表記の追加
setopt extended_history
# beep を無効にする
setopt no_beep
# フローコントロールを無効にする(ctrl + S無効化)
setopt no_flow_control
# Ctrl+Dでzshを終了しない
setopt ignore_eof
# '#' 以降をコメントとして扱う
setopt interactive_comments
# ディレクトリ名だけでcdする
setopt auto_cd
# 同時に起動したzshの間でヒストリを共有する
setopt share_history

### AutoCompletetion
# 拡張Completion有効化
autoload -Uz compinit
compinit
# ../ の後は今いるディレクトリを補完しない
zstyle ':completion:*' ignore-parents parent pwd ..
# sudo の後ろでコマンド名を補完する
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
# ps コマンドのプロセス名補完
zstyle ':completion:*:processes' command 'ps x -o pid,s,args'
 
### KeyBind
# ^R で履歴検索をするときに * でワイルドカードを使用出来るようにする
bindkey '^R' history-incremental-pattern-search-backward

### Git
autoload -Uz vcs_info
setopt prompt_subst
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "%F{magenta}!"
zstyle ':vcs_info:git:*' unstagedstr "%F{yellow}+"
zstyle ':vcs_info:*' formats "%F{cyan}%c%u[%b]%f"
zstyle ':vcs_info:*' actionformats '[%b|%a]'
precmd () { vcs_info }
 
### Prompt
# zshカスタムプロンプト
PROMPT='
[%B%F{blue}%n@%m%f%b:%F{green}%~%f]%F{cyan}$vcs_info_msg_0_%f
%F{yellow}$%f '

